### ISSUE TITLE
Do you have to install Curobo, IsaacGym from third party source code provided

### ISSUE THREAD

**Issue by adithyamurali** [princeton-vl/FetchBench-CORL2024#1]
Can we directly download and use Curobo from https://curobo.org/ or do we have to use the source code provided in `3rd_parties.zip`?

Were there any major code changes that affects the running of the script?

Same question for IsaacGym

**Comment by adithyamurali** [comment]
And thanks for releasing the code @BillHan-Fantast !

**Comment by beininghan** [comment]
Hi Adithya,

IsaacGym should be exactly the same as the public version.

For Curobo 0.6.2, we modified the code to attach the object to the hand given an z-axis offset in the world frame. Moreover, we modified the planning context a little bit for Franka Research 3. I remember the latest 0.7.x also already contains similar functions but small modification is still needed (e.g., ./content/configs/robot/franka_r3.yml).

**Comment by adithyamurali** [comment]
Sounds good thanks!
